[theme]
base = "light"
primaryColor = "#00B25D"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F7F9"
textColor = "#17191C"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
port = 8501
