[theme]
base = "dark"
primaryColor = "#00D46E"
backgroundColor = "#121417"
secondaryBackgroundColor = "#1A1D21"
textColor = "#F2F4F6"
font = "sans serif"

[client]
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
port = 8501
